apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 3
  selector:
    matchLabels:
      env: production
